### ISSUE TITLE
Injecting sample users for testing

### ISSUE THREAD

**Issue by slimandslam** [joscha/play-authenticate#230]
Hi Joscha,
    Do you have a recommended way of injecting some sample users into a Play app
with play-authenticate to make testing easy?  I'd like to have a few sample users in
the database of the Play app and set smtp.mock=true to do testing on our staging site.

-J

**Comment by slimandslam** [comment]
Joscha, if one is using username/password auth, it's not clear how to inject those users. If I put a plaintext password into the yml file, e.g. 

` linkedAccounts:
                 - !!models.LinkedAccount
                     providerUserId: "somepass"
                     providerKey: "password"`

It never gets encrypted.

**Comment by joscha** [comment]
The password provider is somewhat special in that respect - I don't think I ever tried doing that out of the box, so I think you'd either need to adapt the `insert` method to encrypt on the fly (before inserting) oder add the encrypted passwords into the yml file (which is probably better anyway, as otherwise there would be cleartext passwords in your source code).

**Comment by slimandslam** [comment]
I just added the encrypted passwords manually into the yml file.  It works!

J
